### ISSUE TITLE
Critical CSS

### ISSUE THREAD

**Issue by chymz** [universal-vue/uvue#2]
Vue SSR offers a [minimal but powerful critical CSS system](https://ssr.vuejs.org/guide/css.html) but I want make available others solutions like [critical](https://www.npmjs.com/package/critical) package and [critters](https://github.com/GoogleChromeLabs/critters)

**Roadmap:**
- [ ] Generate critical CSS automatically with one page taken from application and apply it on `index.html` template (for SSR sites)
- [ ] Generate critical CSS on each pages (useful for static generated websites)
- [ ] Inject a CSS file created manually and inject it in final HTML output
